apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-of-apps2
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: app2
    server: https://kubernetes.default.svc
  source:
    path: yamls
    repoURL: https://github.com/anilabhabaral/argocd-app.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
