kind: Project
apiVersion: project.openshift.io/v1
metadata:
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    kubernetes.io/metadata.name: app1
  name: app1
spec:
  finalizers:
    - kubernetes
