apiVersion: project.openshift.io/v1
kind: Project
metadata:
  labels:
    argocd.argoproj.io/managed-by: openshift-gitops
    kubernetes.io/metadata.name: app2
    openshift.io/requester: kube:admin
  name: app2
spec:
  finalizers:
  - kubernetes
