apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jboss-helloworld-route
spec:
  path: {{ .Values.route.path }}
  port:
    targetPort: {{ .Values.route.targetPort }}
  to:
    kind: Service
    name: jboss-helloworld-service
    weight: 100
  wildcardPolicy: None
