apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: jboss-helloworld-service-route
spec:
  path: "/helloworld"
  port:
    targetPort: 8080
  to:
    kind: Service
    name: jboss-helloworld-service
    weight: 100
  wildcardPolicy: None
