apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app-of-apps
spec:
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: app-of-apps
    repoURL: https://github.com/anilabhabaral/argocd-app/
    targetRevision: HEAD
  syncPolicy:
    automated: {}
